title: "// this might work..."
email: sarah@sooperduper.com
name: "Sarah Kuehnle"
description: "Sarah Kuehnle is generalist who loves front-end development and product design. This blog details her experiences making a career change from product management to design and engineering."
url: http://ursooperduper.github.io
twitter_username: ursooperduper
github_username: ursooperduper
instagram_username: ursooperduper
dribbble_username: ursooperduper
linkedin_username: sarahkuehnle
exclude: ["tmux-ursoop-sess"]
encoding: "utf-8"
baseurl: "/"
markdown: kramdown
kramdown:
    input: GFM
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"
