title: "// this might work..."
email: sarah@sooperduper.com
name: "Sarah Kuehnle"
description: "Sarah Kuehnle is a Product Designer, Prototyper, Developer, and productivity enthusiast."
url: http://ursooperduper.github.io
twitter_username: ursooperduper
github_username: ursooperduper
instagram_username: ursooperduper
dribbble_username: ursooperduper
linkedin_username: sarahkuehnle
exclude:
- node_modules
- tmux-ursoop-sess
- vendor
encoding: "utf-8"
baseurl: "/"
markdown: kramdown
kramdown:
    input: GFM
lsi: false
excerpt_separator: "\n\n"
collections:
  projects:
    output: true
    permalink: /:path/
jekyll-crosspost_to_medium:
  enabled: true
  cache: .jekyll-crosspost_to_medium
  status: draft
  license: all-rights-reserved
  backdate: true
