title: "// this might work..."
email: sarah@sooperduper.com
name: Sarah Kuehnle
description: "Sarah Kuehnle is currently attending Hacker School (F1-14). This blog documents her experiences making a career change from design and product to engineering.\n\nIf debugging this is wrong, I don't want to be right."
twitter_username: ursooperduper
github_username: ursooperduper
instagram_username: ursooperduper
dribbble_username: ursooperduper
linkedin_username: sarahkuehnle
exclude: ["tmux-ursoop-sess"]
encoding: "utf-8"
baseurl: "/"
