title: "// this might work..."
email: sarah@sooperduper.com
name: "Sarah Kuehnle"
description: "Sarah Kuehnle is a generalist interested in product design, front-end and mobile development, and you."
url: http://ursooperduper.github.io
twitter_username: ursooperduper
github_username: ursooperduper
instagram_username: ursooperduper
dribbble_username: ursooperduper
linkedin_username: sarahkuehnle
exclude:
- node_modules
- tmux-ursoop-sess
- vendor
encoding: "utf-8"
baseurl: "/"
markdown: kramdown
kramdown:
    input: GFM
lsi: false
excerpt_separator: "\n\n"
gems:
- jekyll-gist
collections:
  projects:
    output: true
    permalink: /:path/
